import Head from 'next/head'
import { useState } from 'react'
import Footer from '../components/Footer'
import { Header } from '../components/Header'
import { Sidebar } from '../components/Sidebar'
import '../styles/globals.css'

function MyApp ({ Component, pageProps }) {
  const [showSidebar, setShowSidebar] = useState(false)

  return (
    <>
      <Head>
        <title>Spotify - Reproductor Web</title>
        <meta name='description' content='Generated by Replica de spotify' />
        <link rel='icon' type='image/svg+xml' href='https://cdn-icons-png.flaticon.com/512/174/174872.png' />
      </Head>
      <div className='bg-gradient-to-t from-spotify-gray via-spotify-gray  to-[#1E1E1E] min-h-screen '>
        <Sidebar showSidebar={showSidebar} setShowSidebar={setShowSidebar} />
        <Header setShowSidebar={setShowSidebar} />
        <main>
          <Component {...pageProps} />
        </main>
        <Footer />
      </div>
    </>
  )
}

export default MyApp
